<a href="https://colab.research.google.com/github/shv-om/predictive-analytics-models/blob/main/Shivam_Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [ ]:
dataset = pd.read_csv('/content/adult.csv')
dataset.head(10)

39          State-gov   77516      Bachelors   13           Never-married  \
0  50   Self-emp-not-inc   83311      Bachelors   13      Married-civ-spouse   
1  38            Private  215646        HS-grad    9                Divorced   
2  53            Private  234721           11th    7      Married-civ-spouse   
3  28            Private  338409      Bachelors   13      Married-civ-spouse   
4  37            Private  284582        Masters   14      Married-civ-spouse   
5  49            Private  160187            9th    5   Married-spouse-absent   
6  52   Self-emp-not-inc  209642        HS-grad    9      Married-civ-spouse   
7  31            Private   45781        Masters   14           Never-married   
8  42            Private  159449      Bachelors   13      Married-civ-spouse   
9  37            Private  280464   Some-college   10      Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   
5       Other-service   Not-in-family   Black   Female      0   0   16   
6     Exec-managerial         Husband   White     Male      0   0   45   
7      Prof-specialty   Not-in-family   White   Female  14084   0   50   
8     Exec-managerial         Husband   White     Male   5178   0   40   
9     Exec-managerial         Husband   Black     Male      0   0   80   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K  
5         Jamaica   <=50K  
6   United-States    >50K  
7   United-States    >50K  
8   United-States    >50K  
9   United-States    >50K

In [ ]:
X = dataset.iloc[:, :14].values
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

label_index = [1, 3, 5, 6, 7, 8, 9, 13]

for i in label_index:
    X[:, i] = le.fit_transform(X[:, i])

X

array([[50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       [53, 4, 234721, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)

In [ ]:
y[:] = le.fit_transform(y[:])
y

array([0, 0, 0, ..., 0, 0, 1], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

y_train = y_train.astype('int')
y_test = y_test.astype('int')


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train, X_test

(array([[-0.33671637,  0.08954379,  0.0774814 , ..., -0.21641578,
         -0.03803174,  0.29340232],
        [ 1.50131423,  0.08954379, -1.2233263 , ..., -0.21641578,
         -0.44494335,  0.29340232],
        [-1.29249228,  0.08954379, -0.01900693, ..., -0.21641578,
         -0.03803174,  0.29340232],
        ...,
        [ 0.32497465,  1.46006051,  1.15587921, ..., -0.21641578,
         -0.85185497,  0.29340232],
        [-1.29249228,  2.14531887, -1.43948496, ..., -0.21641578,
          0.77579149,  0.29340232],
        [ 0.76610199,  0.77480215, -0.76693938, ..., -0.21641578,
         -0.68909032,  0.29340232]]),
 array([[ 0.10441098,  0.77480215,  0.0330166 , ..., -0.21641578,
         -0.03803174,  0.29340232],
        [ 0.54553832,  0.08954379, -0.01944594, ..., -0.21641578,
          0.36887988,  0.29340232],
        [-0.41023759, -2.65148965,  0.11866311, ..., -0.21641578,
         -0.03803174, -3.01172696],
        ...,
        [ 0.10441098,  0.08954379,  1.75895511, ..., -

In [ ]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

In [ ]:
print("Confusion Matrix\n", cm)

Confusion Matrix
 [[5898  295]
 [1307  640]]


In [ ]:
print("Accuracy:", ac)

Accuracy: 0.8031941031941032
